### ISSUE TITLE
About scale transformation of imputed gene expression by MIST

### ISSUE THREAD

**Issue by yangj99** [linhuawang/spImpute#3]
Hi, Dr. Lin. You have introduced a simple but fairly powerful imputation program of spatial transcriptome!
I have applied your program over several datasets and found the imputed expression has relatively large number overall, like hundreds to thousands after the normalization and log transformation. This confused me since I would like to compare the result from several imputation or denoising methods at an unified standard, and may evaluate via AUC curve. Would you like to give me a hint of how to transform the MIST imputed expression back to the original scale?

Below is the original visium expression data:
![image](https://github.com/linhuawang/MIST/assets/65137824/a08c08d4-cab6-451c-a42f-ba38852309b9)
and the MIST imputed data:
![image](https://github.com/linhuawang/MIST/assets/65137824/ef705ee4-7351-4eb4-9f78-00519d53d80b)

**Comment by MatteoRiva95** [comment]
Hello @yangj99 sorry for the off-topic question, but how did you run MIST?
Because I am following both Tutorial1 and the Rest.py script, I launched the following command:

imputed = rd_1.impute(method='MIST', ncores=70, nExperts=15)
Imputing layer CPM
[Start][Region] 0 / 35 | [Spots] 125 | 125 / 4466.

and it is taking a lot of time to finish. Did you use the same command? Did it take ages to finish?
Moreover, do you know what nExperts is used for? Because I do not understand :(

Can you help me please?
Thank you in advance!

**Comment by linhuawang** [comment]
Hi, @yangj99, sorry for the late reply. The imputed value is scaled at counts per million (CPM), while your input is raw counts.
